### ISSUE TITLE
Rename to oslc4js-sample-ldp-server

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/ldp-app#6]
@jamsden do you think it will better reflect its purpose?

**Comment by jamsden** [comment]
I guess, but it's kind of a long name with some redundant information in it - oslc4js, and sample.

**Comment by berezovskyi** [comment]
Well, I wanted to allow anyone who reads the name to understand that it's part of oslc4js and is sample code.

**Comment by jamsden** [comment]
But that should be clear from the artifact group and id.

**Comment by berezovskyi** [comment]
a) this is not a java app
b) I don't see any of that in the OSLC org

**Comment by berezovskyi** [comment]
Just had to go back to the repo again yesterday to check which artifact is the new client and which is not. Definitely not ok if the newcomers would be confused like this.

**Comment by jamsden** [comment]
The implementation does use SPARQL UPDATE, but the sample app use Apache Jena Fuseki. So I think the name is ok.
